qanchiCricketArena/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField
from wtforms.validators import DataRequired,Length,Email,EqualTo,ValidationError




class postForm(FlaskForm):
    title=StringField('Title',validators=[DataRequired()])
    content=TextAreaField('Content',validators=[DataRequired()])
    submit=SubmitField('Post')

qanchiCricketArena/main/routes.py
from flask import render_template,request,Blueprint
from qanchiCricketArena.models import post
from qanchiCricketArena import db
mainB=Blueprint('mainB',__name__)


@mainB.route("/")
@mainB.route("/home")
def homePageFunc():
    page=request.args.get('page',1,type=int)
    posts=post.query.order_by(post.datePosted.desc()).paginate(page=page,per_page=7)

    return render_template('home.html',posts=posts)


@mainB.route("/QSAHome")
def QSAHome():
    return render_template('QSAHome.html')



@mainB.route("/about")
def aboutPageFunc():
    return render_template('about.html',title='About')

@mainB.route('/create_db_and_upload_folder')
def create_db():
    # Create db
    db.create_all()
    # Create the "upload" folder if it doesn't exist

    return 'Database and upload folder created successfully!'

qanchiCricketArena/posts/routes.py
from flask import Blueprint
from flask import render_template,url_for,flash,redirect,request,abort
from qanchiCricketArena.models import user,post
from qanchiCricketArena.posts.forms import postForm
from qanchiCricketArena import db
from flask_login import current_user,login_required



postsB=Blueprint('postsB',__name__)


@postsB.route("/post/new",methods=['POST','GET'])
@login_required
def newPostPageFunc():
    form=postForm()
    if form.validate_on_submit():
        post1=post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post1)
        db.session.commit()
        flash("your post has been created",'succcess')
        return redirect(url_for('mainB.homePageFunc'))
    return render_template('newPost.html',title='Post',legend='New Post',form=form)



@postsB.route("/post/<int:post_id>",methods=['POST','GET'])
@login_required
def postPageFunc(post_id):
    post1=post.query.get_or_404(post_id)
    return render_template('post.html',title=post1.title,post=post1)

@postsB.route("/post/<int:post_id>/update",methods=['POST','GET'])
@login_required
def updatePostPageFunc(post_id):
    post1=post.query.get_or_404(post_id)
    if post1.author!=current_user:
        abort(403)
    form=postForm()
    if form.validate_on_submit():
        post1.title=form.title.data
        post1.content=form.content.data
        db.session.commit()
        flash("Your post has been updated",'success')
        return redirect(url_for('postsB.postPageFunc',post_id=post1.id))
    elif request.method=='GET':
        form.title.data=post1.title
        form.content.data=post1.content
    return render_template('newPost.html',title='Update Post',legend='Update Post',form=form)


@postsB.route("/post/<int:post_id>/delete",methods=['POST'])
@login_required
def deletePostPageFunc(post_id):
    post1 = post.query.get_or_404(post_id)
    if post1.author != current_user:
        abort(403)
    db.session.delete(post1)
    db.session.commit()
    flash("Your post has been deleted",'success')
    return redirect(url_for('mainB.homePageFunc'))



@postsB.route("/user/<string:username>")
@login_required
def userPostFunc(username):
    page=request.args.get('page',1,type=int)
    user1=user.query.filter_by(username=username).first_or_404()
    posts=post.query.filter_by(author=user1).order_by(post.datePosted.desc()).paginate(page=page,per_page=5)
    return render_template ('userPost.html',posts=posts,user=user1)

qanchiCricketArena/users/routes.py
from flask import Blueprint
from flask import render_template,url_for,flash,redirect,request,abort
from qanchiCricketArena.models import user
from qanchiCricketArena.users.forms import registrationForm,loginForm,updateAccountForm,requestResetForm,resetPasswordForm
from qanchiCricketArena import db,bcrypt
from flask_login import login_user,current_user,logout_user,login_required
from qanchiCricketArena.users.utils import savePicture,sendResetEmail

usersB=Blueprint('usersB',__name__)





#routes

@usersB.route("/registration",methods=['POST','GET'])
def registrationPageFunc():
    if current_user.is_authenticated:
        return redirect(url_for('mainB.homePageFunc'))
    form=registrationForm()
    if form.validate_on_submit():
        hashedPassword=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user1=user(username=form.username.data,email=form.email.data,password=hashedPassword)
        db.session.add(user1)
        db.session.commit()
        flash(f"Your account has been created !You are now able to login",'success')
        return redirect(url_for('usersB.loginPageFunc'))
    return render_template('registration.html',form=form)




@usersB.route("/login",methods=['POST','GET'])
def loginPageFunc():
    if current_user.is_authenticated:
        return redirect(url_for('mainB.homePageFunc'))
    form=loginForm()
    if form.validate_on_submit():
        user1=user.query.filter_by(email=form.email.data).first()
        if user1 and bcrypt.check_password_hash(user1.password,form.password.data):
            login_user(user1,remember=form.rememberMe.data)
            nextPage=request.args.get('next')
            return redirect(url_for('usersB.accountPageFunc')) if nextPage else redirect(url_for('mainB.homePageFunc'))
        else:
            flash(f"Login Unsuccessful, please try again with valid email and password",'danger')
    return render_template('login.html',title='Login',form=form)


@usersB.route("/logout")
def logoutPageFunc():
    logout_user()
    return render_template('logout.html',title='Logout')





@usersB.route("/account",methods=['POST','GET'])
@login_required
def accountPageFunc():
    form=updateAccountForm()
    if form.validate_on_submit():
        if form.picture:
            pictureFile=savePicture(form.picture.data)
            current_user.imageFile=pictureFile
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('your account has been updated','success')
        return redirect(url_for('usersB.accountPageFunc'))
    elif request.method=='GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
    imageFile=url_for('static',filename=f'profilePics/{current_user.imageFile}')
    return render_template('account.html',title='Account',imageFile=imageFile,form=form)




@usersB.route("/resetPassword",methods=['POST','GET'])
def resetRequestPageFunc():
    if current_user.is_authenticated:
        return redirect(url_for('main.homePageFunc'))
    form=requestResetForm()
    if form.validate_on_submit():
        user1=user.query.filter_by(email=form.email.data).first()
        sendResetEmail(user1)
        flash('An Email has been sent with instruction to reset your password')
        return redirect(url_for('users.loginPageFunc'))
    return render_template ('resetRequest.html',form=form,title='Reset Password')



@usersB.route("/resetPassword/<token>",methods=['POST','GET'])
def resetTokenPageFunc(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.homePageFunc'))
    user1=user.verify_reset_token(token)
    if user1 is None:
        flash('This is invalid or expires token')
        return redirect(url_for('users.resetRequestPageFunc'))
    form=resetPasswordForm()
    if form.validate_on_submit():
        hashedPassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user1.password=hashedPassword
        db.session.commit()
        flash(f"Your password has been updated !You are now able to login", 'success')
        return redirect(url_for('users.loginPageFunc'))
    return render_template ('resetToken.html',form=form,title='Reset Password')

qanchiCricketArena/templates/QSAHome.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>QSA Home</title>
	<link rel="icon" type="image/png" href="../static/images/cricket.png" >
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='QSAHome.css') }}">
	<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

	
</head>

<body>
	<header class="header">
		<nav class="navbar">
			<a href="#home" class="active">Events</a>
			<a href="#about">Rankings</a>
			<a href="#services">Athletes</a>
			<a href="#portfolio">Umer Sohail Contender Series</a>
			<a href="#contact">News</a>
			
		</nav>
		
		<a href="#" class="logo">QSA</a>
		<i class='bx bx-menu' id="menu-icon"></i>
		
		<nav class="navbar">
			<a href="#services">QSA1</a>
			<a href="#portfolio">Bookings</a>
			<a href="#contact">Watch</a>
			<a href="#contact">Shop</a>
		</nav>
	
	</header>
	
	
<!--	home section-->
		<section class="home" id="home">
		<div class="home-content">
			<h3>Hello, It's me</h3>
			<h1>M Umer Sohail khan</h1>
			<h3>And I'm a <span class="multiple-text"></span></h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab distinctio dolorem dolorum ducimus eaque,
				excepturi expedita facilis illo illum magnam
				nobis odit pariatur quibusdam reiciendis sint temporibus voluptates. Quibusdam, unde!</p>
			<div class="social-media">
				<a href="#"><i class='bx bxl-facebook-square' ></i></a>
				<a href="#"><i class='bx bxl-instagram' ></i></a>
				<a href="#"><i class='bx bxl-linkedin-square' ></i></a>
				<a href="#"><i class='bx bxl-github' ></i></a>
			</div>
			<a href="#" class="btn">Download CV</a>
		</div>
		<div class="home-image">
			<img src="images/homeimg.png" alt="">
		</div>
	</section>
	
	

  <script src="../static/JsFiles/scripts.js"></script>

</body>
</html>

qanchiCricketArena/templates/about.html
{% extends 'layout.html' %}
{% block content %}
		<h1>about page</h1>
{% endblock content %}

qanchiCricketArena/templates/account.html
{% extends 'layout.html' %}
{% block content %}
   <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ imageFile }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
	   <form method="POST" action="" enctype="multipart/form-data">
		{{form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Account Info</legend>
			<div class="form-group">
				{{ form.username.label(class='form-control-label') }}
				{% if form.username.errors %}
					{{ form.username(class='form-control form-control-lg is-invalid') }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.username(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class='form-control-label') }}
					{% if form.email.errors %}
						{{ form.email(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.email(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			
			<div class="form-group">
				{{ form.picture.label() }}
				{{ form.picture(class='form-control-file') }}
					{% if form.picture.errors %}
							{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span></br>
							{% endfor %}
					{% endif %}
			</div>
			
		</fieldset>
		<div class="form-group">
				{{ form.submit(class='btn btn-outline-info') }}
			</div>
	
	</form>
   </div>
{% endblock content %}

qanchiCricketArena/templates/bookingPage.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ legend }}</legend>
			<div class="form-group">
				{{ form.timeBooked.label(class='form-control-label') }}
					{% if form.timeBooked.errors %}
						{{ form.timeBooked(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.timeBooked.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.timeBooked(class='form-control form-control-lg') }}
				{% endif %}
			</div>
				<div class="form-group">
				{{ form.dateBooked.label(class='form-control-label') }}
					{% if form.dateBooked.errors %}
						{{ form.dateBooked(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.dateBooked.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.dateBooked(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			
			
			
		</fieldset>
		<div class="form-group">
				{{form.submit(class='btn btn-outline-info')}}
			</div>
	</form>
</div>
{% endblock content %}

qanchiCricketArena/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profilePics/'+post.author.imageFile) }}" alt="">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2" href="{{ url_for('postsB.userPostFunc',username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.datePosted.strftime('%Y-%m-%d') }}</small>
		</div>
		<h2><a class="article-title" href="{{ url_for('postsB.postPageFunc',post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1, right_current=2) %}
	{% if page_num %}
		{% if posts.page==page_num %}
		<a class="btn btn-info-info mb-4"  href="{{ url_for('mainB.homePageFunc',page = page_num) }}">{{ page_num }}</a>
		{% else %}
		<a class="btn btn-outline-info mb-4"  href="{{ url_for('mainB.homePageFunc',page = page_num) }}">{{ page_num }}</a>
		{% endif %}
	{% else %}
	...
	{% endif %}
{% endfor %}


{% endblock content %}

qanchiCricketArena/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('mainB.homePageFunc')}}">Home</a>
              <a class="nav-item nav-link" href="{{url_for('mainB.aboutPageFunc')}}">About</a>
            </div>
            <!-- Navbar Right Side -->
	          
            <div class="navbar-nav">
	            {% if current_user.is_authenticated %}
	            <a class="nav-item nav-link" href="{{url_for('usersB.logoutPageFunc')}}">Logout</a>
 	            <a class="nav-item nav-link" href="{{url_for('usersB.accountPageFunc')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('postsB.newPostPageFunc')}}">New Post</a>

	          {% else %}
	            <a class="nav-item nav-link" href="{{url_for('usersB.loginPageFunc')}}">Login</a>
              <a class="nav-item nav-link" href="{{url_for('usersB.registrationPageFunc')}}">Register</a>
	          {% endif %}
            
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
	        {% with messages=get_flashed_messages(with_categories=true) %}
	            {%if messages %}
	                {% for category,message in messages %}
	                <div class="alert alert-{{category }}">
	                {{ message }}
	                </div>
	                {% endfor %}
	            {% endif %}
	        {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

qanchiCricketArena/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Today</legend>
			<div class="form-group">
				{{ form.email.label(class='form-control-label') }}
					{% if form.email.errors %}
						{{ form.email(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.email(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class='form-control-label') }}
					{% if form.password.errors %}
					{{ form.password(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class='form-control form-control-lg') }}

					{% endif %}
			</div>
			 <div class="form-check">
                    {{ form.rememberMe(class="form-check-input") }}
                    {{ form.rememberMe.label(class="form-check-label") }}
                </div>
		</fieldset>
		<div class="form-group">
				{{form.submit(class='btn btn-outline-info')}}
			<small class="text-muter ml-2">
			<a href="{{url_for('usersB.resetRequestPageFunc')}}">Forget Password</a>
		</small>
			</div>
		
			</form>

		<div class="border-top pt-3">
				<small class="text-muted">
					Don't have an Account? <a class="ml-2" href="{{url_for('usersB.registrationPageFunc')}}">Sign Up</a>
				</small>
		</div>
</div>

{% endblock content %}

qanchiCricketArena/templates/logout.html
{% extends 'layout.html' %}
{% block content %}
		<h3>You account has been logged out</h3>
{% endblock content %}

qanchiCricketArena/templates/newPost.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ legend }}</legend>
			<div class="form-group">
				{{ form.title.label(class='form-control-label') }}
					{% if form.title.errors %}
						{{ form.title(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.title(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class='form-control-label') }}
					{% if form.content.errors %}
					{{ form.content(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class='form-control form-control-lg') }}

					{% endif %}
			</div>
			
		</fieldset>
		<div class="form-group">
				{{form.submit(class='btn btn-outline-info')}}
			</div>
	</form>
</div>
{% endblock content %}

qanchiCricketArena/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profilePics/'+post.author.imageFile) }}" alt="">
	<div class="media-body">
		<div class="article-metadata">
			
			<a class="mr-2" href="{{ url_for('postsB.userPostFunc',username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.datePosted.strftime('%Y-%m-%d') }}</small>
			{% if post.author==current_user %}
			<div>
				<a class="btn btn-secondary btn-sm m-1" href="{{ url_for('postsB.updatePostPageFunc',post_id=post.id) }}">Update</a>
				<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
					Delete
				</button>
			</div>
			{% endif %}
		</div>
		<h2 class="article-title">{{ post.title }}</h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>

<!-- Modal -->
<div class="modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				<form action="{{ url_for('postsB.deletePostPageFunc', post_id=post.id) }}" method="post">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

qanchiCricketArena/templates/registration.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Today</legend>
			<div class="form-group">
				{{ form.username.label(class='form-control-label') }}
				{% if form.username.errors %}
					{{ form.username(class='form-control form-control-lg is-invalid') }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.username(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class='form-control-label') }}
					{% if form.email.errors %}
						{{ form.email(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
					</div>
				{% else %}
					{{ form.email(class='form-control form-control-lg') }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class='form-control-label') }}
					{% if form.password.errors %}
					{{ form.password(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class='form-control form-control-lg') }}

					{% endif %}
			</div>
			<div class="form-group">
				{{ form.confirmPassword.label(class='form-control-label') }}
					{% if form.confirmPassword.errors %}
						{{ form.confirmPassword(class='form-control form-control-lg is-invalid') }}
						<div class="invalid-feedback">
							{% for error in form.confirmPassword.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
						{% else %}
							{{ form.confirmPassword(class='form-control form-control-lg') }}
					{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
				{{ form.submit(class='btn btn-outline-info') }}
			</div>
		<div class="border-top pt-3">
				<small class="text-muted">
					Already have an Account? <a class="ml-2" href="{{url_for('usersB.loginPageFunc')}}">Sign In</a>
				</small>
		</div>
	</form>
</div>

{% endblock content %}

qanchiCricketArena/templates/userPost.html
{% extends "layout.html" %}
{% block content %}
<h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profilePics/'+post.author.imageFile) }}" alt="">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2" href="{{ url_for('postsB.userPostFunc',username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.datePosted.strftime('%Y-%m-%d') }}</small>
		</div>
		<h2><a class="article-title" href="{{ url_for('postsB.postPageFunc',post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1, right_current=2) %}
	{% if page_num %}
		{% if posts.page==page_num %}
		<a class="btn btn-info-info mb-4"  href="{{ url_for('postsB.userPostFunc',username=user.username,page = page_num) }}">{{ page_num }}</a>
		{% else %}
		<a class="btn btn-outline-info mb-4"  href="{{ url_for('postsB.userPostFunc',username=user.username,page = page_num) }}">{{ page_num }}</a>
		{% endif %}
	{% else %}
	...
	{% endif %}
{% endfor %}


{% endblock content %}